#!/bin/sh
# ==============================================================================
# Take down the S6 supervision tree when Shairport Sync fails
# ==============================================================================

if [ "$1" -ne 0 ] && [ "$1" -ne 256 ]; then
  echo "Shairport Sync exited with code $1"
fi
